In [17]:
# Import our tools
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

print("All libraries loaded successfully!")

All libraries loaded successfully!

In [18]:
dp=sns.load_dataset('titanic')
dp

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [19]:
dp.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [20]:
dp['age'].fillna(dp['age'].median(), inplace = True)

dp['embarked'].fillna(dp['embarked'].mode()[0], inplace = True)

dp['embark_town'].fillna(dp['embark_town'].mode()[0], inplace = True)

C:\Users\acer\AppData\Local\Temp\ipykernel_13088\1817930225.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dp['age'].fillna(dp['age'].median(), inplace = True)
C:\Users\acer\AppData\Local\Temp\ipykernel_13088\1817930225.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dp['embarked'].fillna(dp['embarked'].mode()[0], inplace = True)
C:\Users\acer\AppData\Local\Temp\ipykernel_13088\1817930225.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dp['embark_town'].fillna(dp['embark_town'].mode()[0], inplace = True)

In [21]:
dp.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [22]:
dp=dp.drop(columns=['embarked','class','deck','alive', 'who', 'adult_male', 'alone'])
dp

     survived  pclass     sex   age  sibsp  parch     fare  embark_town
0           0       3    male  22.0      1      0   7.2500  Southampton
1           1       1  female  38.0      1      0  71.2833    Cherbourg
2           1       3  female  26.0      0      0   7.9250  Southampton
3           1       1  female  35.0      1      0  53.1000  Southampton
4           0       3    male  35.0      0      0   8.0500  Southampton
..        ...     ...     ...   ...    ...    ...      ...          ...
886         0       2    male  27.0      0      0  13.0000  Southampton
887         1       1  female  19.0      0      0  30.0000  Southampton
888         0       3  female  28.0      1      2  23.4500  Southampton
889         1       1    male  26.0      0      0  30.0000    Cherbourg
890         0       3    male  32.0      0      0   7.7500   Queenstown

[891 rows x 8 columns]

In [23]:
dp['sex']=dp['sex'].map({'male':1, 'female':2})
# dp['who']=dp['who'].map({'man':1,'woman':2,'child':3})
# dp['adult_male']=dp['adult_male'].map({True:1,False:0})
dp['embark_town']=dp['embark_town'].map({'Southampton':1,'Cherbourg':2,'Queenstown':3})
# dp['alone']=dp['alone'].map({False:0,True:1})
dp.head()

   survived  pclass  sex   age  sibsp  parch     fare  embark_town
0         0       3    1  22.0      1      0   7.2500            1
1         1       1    2  38.0      1      0  71.2833            2
2         1       3    2  26.0      0      0   7.9250            1
3         1       1    2  35.0      1      0  53.1000            1
4         0       3    1  35.0      0      0   8.0500            1

In [24]:
x = dp.drop(columns=['survived'])
y = dp['survived']

print('X shape:',x.shape)
print('Y shape:',y.shape)

X shape: (891, 7)
Y shape: (891,)

In [25]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=22)

print('training set:', x_train.shape)
print('test set:', x_test.shape)

training set: (712, 7)
test set: (179, 7)

In [26]:
model = LogisticRegression(max_iter=1000)
model.fit(x_train, y_train)

print('model trained successfully')

model trained successfully

In [27]:
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)

print(f'accuracy:{accuracy * 100:.2f}%')

cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix')
print(cm)

accuracy:77.65%
Confusion Matrix
[[93 17]
 [23 46]]

In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.85      0.82       110
           1       0.73      0.67      0.70        69

    accuracy                           0.78       179
   macro avg       0.77      0.76      0.76       179
weighted avg       0.77      0.78      0.77       179

In [29]:
from sklearn.ensemble import RandomForestClassifier

# Create Random Forest model
# n_estimators = number of trees in the forest
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train
model_rf.fit(x_train, y_train)

print("Random Forest trained successfully!")

Random Forest trained successfully!

In [31]:
# Make predictions
y_pred_rf = model_rf.predict(x_test)

# Evaluate
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Logistic Regression Accuracy: 77.65%")
print(f"Random Forest Accuracy: {accuracy_rf * 100:.2f}%")
print(f"\nImprovement: {(accuracy_rf * 100) - 77.65:.2f}%")

# Full report
print(classification_report(y_test, y_pred_rf))

Logistic Regression Accuracy: 77.65%
Random Forest Accuracy: 79.89%

Improvement: 2.24%
              precision    recall  f1-score   support

           0       0.84      0.83      0.83       110
           1       0.73      0.75      0.74        69

    accuracy                           0.80       179
   macro avg       0.79      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179